image: maven:3.9.7-eclipse-temurin-21-alpine

stages:
  - compile
  - test
  - package

cache:
  paths:
    - .m2/repository
    - target

variables:
  MAVEN_CLI_OPTS: "--batch-mode"

include:
  - local: 'patient-service/gitlab.yml'