image: maven:3.9.7-eclipse-temurin-21-alpine

stages:
  - compile
  - test
  - package
  - docker_build

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_CLI_OPTS: "--batch-mode"

include:
  - local: 'patient-service/gitlab.yml'
  - local: 'discovery-service/gitlab.yml'
  - local: 'gateway-service/gitlab.yml'
  - local: 'frontend-service/gitlab.yml'
  - local: 'notes-service/gitlab.yml'
  - local: 'diabetes-report-service/gitlab.yml'