services:

  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/:/docker-entrypoint-initdb.d/
    networks:
      - internal

  mongo:
    image: mongo:8.0.0-rc15-jammy
    restart: on-failure
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - internal

  discovery-service:
    image: registry.gitlab.com/davelog/medilabo-solutions/discovery-service:1.0.0
    ports:
      - "8761:8761"
    networks:
      - internal

  gateway-service:
    image: registry.gitlab.com/davelog/medilabo-solutions/gateway-service:1.0.0
    ports:
      - "8080:8080"
    networks:
      - internal
    environment:
      SPRING_DATASOURCE_URL: r2dbc:mysql://mysql:3306/userdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootroot
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql
      - discovery-service

  patient-service:
    image: registry.gitlab.com/davelog/medilabo-solutions/patient-service:1.0.0
    ports:
      - "8081:8081"
    networks:
      - internal
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/patients
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootroot
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql
      - discovery-service
      - gateway-service

  notes-service:
    image: registry.gitlab.com/davelog/medilabo-solutions/notes-service:1.0.0
    ports:
      - "8082:8082"
    networks:
      - internal
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: patient_notes
    depends_on:
      - mongo
      - discovery-service
      - gateway-service

  diabetes-report-service:
    image: registry.gitlab.com/davelog/medilabo-solutions/diabetes-report-service:1.0.0
    ports:
      - "8083:8083"
    networks:
      - internal
    depends_on:
      - discovery-service
      - patient-service
      - notes-service

  frontend-service:
    image: registry.gitlab.com/davelog/medilabo-solutions/frontend-service:1.0.0
    ports:
      - "3000:80"
    networks:
      - internal
    depends_on:
      - gateway-service


volumes:
  mysql_data:
  mongo_data:

networks:
  internal:
    driver: bridge
