services:

  patient-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: patients
    ports:
      - "3307:3306"
    volumes:
      - patient_data:/var/lib/mysql
    networks:
      - internal

  user-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: userdb
    ports:
      - "3308:3306"
    volumes:
      - user_data:/var/lib/mysql
    networks:
      - internal

  discovery-service:
    build:
      context: .
      dockerfile: discovery-service/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - internal

  gateway-service:
    build:
      context: .
      dockerfile: gateway-service/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - internal
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://user-db:3306/userdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootroot
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - user-db
      - discovery-service

  patient-service:
    build:
      context: .
      dockerfile: patient-service/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - internal
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://patient-db:3306/patients
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootroot
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - patient-db
      - discovery-service
      - gateway-service

volumes:
  patient_data:
  user_data:

networks:
  internal:
    driver: bridge