services:

  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./patient-service/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal

  mongo:
    image: mongo:8.0.0-rc15-jammy
    restart: on-failure
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
      - ./notes-service/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - internal

  discovery-service:
    build:
      context: .
      dockerfile: discovery-service/Dockerfile
    restart: on-failure
    ports:
      - "8761:8761"
    networks:
      - internal

  gateway-service:
    build:
      context: .
      dockerfile: gateway-service/Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - internal
    environment:
      SPRING_DATASOURCE_URL: r2dbc:mysql://mysql:3306/userdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootroot
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql
      - discovery-service

  patient-service:
    build:
      context: .
      dockerfile: patient-service/Dockerfile
    restart: on-failure
    ports:
      - "8081:8081"
    networks:
      - internal
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/patients
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootroot
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql
      - discovery-service
      - gateway-service

  notes-service:
    build:
      context: .
      dockerfile: notes-service/Dockerfile
    restart: on-failure
    ports:
      - "8082:8082"
    networks:
      - internal
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: patient_notes
    depends_on:
      - mongo
      - discovery-service
      - gateway-service

  diabetes-report-service:
    build:
      context: .
      dockerfile: diabetes-report-service/Dockerfile
    restart: on-failure
    ports:
      - "8083:8083"
    networks:
      - internal
    depends_on:
      - discovery-service
      - patient-service
      - notes-service

  frontend-service:
    build:
      context: .
      dockerfile: frontend-service/Dockerfile
    restart: on-failure
    ports:
      - "3000:80"
    networks:
      - internal
    depends_on:
      - gateway-service


volumes:
  mysql_data:
  mongo_data:

networks:
  internal:
    driver: bridge