server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/patient/**
          filters:
            - RewritePath=/patient/?(?<segment>.*), /$\{segment}

        - id: frontend-service
          uri: lb://frontend-service
          predicates:
            - Path=/frontend/**
          filters:
            - RewritePath=/frontend/?(?<segment>.*), /$\{segment}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true