server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/patient/**
          filters:
            - RewritePath=/patient/?(?<segment>.*), /$\{segment}

        - id: frontend-service
          uri: lb://frontend-service
          predicates:
            - Path=/frontend/**
          filters:
            - RewritePath=/frontend/?(?<segment>.*), /$\{segment}
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
              - "http://localhost:5173"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers:
              - "*"
            allow-credentials: true
  r2dbc:
    url: r2dbc:mysql://user-db:3306/userdb?serverTimezone=UTC
    username: root
    password: rootroot
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 648209968703-25m2abibg15g7v1sbjbetgp6dq72fdvo.apps.googleusercontent.com
            client-secret: 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

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true