image: maven:latest

stages:
  - build
  - test
  - package

build:
  stage: build
  script:
    - mvn clean compile

test:
  stage: test
  script:
    - mvn test

package:
  stage: package
  script:
    - mvn -Dmaven.test.skip=true package
  artifacts:
    paths:
      - target/*.jar