server:
  port: 8083

spring:

  application:
    name: diabetes-report-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true